# ============LICENSE_START=======================================================
# dcaegen2-collectors-ves
# ================================================================================
# Copyright (C) 2020 NOKIA
# ================================================================================
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============LICENSE_END=========================================================

apiVersion: v1
kind: ConfigMap
metadata:
  name: ves-influxdb-conf
  labels:
    name: ves-influxdb-conf
  namespace: onap
data:
  influxdb.conf: |-
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

    [[collectd]]
      enabled = true
      bind-address = ":25826"
      database = "collectd"
      retention-policy = ""
      batch-size = 5000
      batch-pending = 10
      batch-timeout = "10s"
      read-buffer = 0
      typesdb = "/usr/share/collectd/types.db"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ves-influxdb-types
  labels:
    name: ves-influxdb-types
  namespace: onap
data:
  types.db: |-
    cpu                     value:DERIVE:0:U
    memory                  value:GAUGE:0:281474976710656
    percent                 value:GAUGE:0:100.1
