name: Submodule Changes CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3


    # Set up Java
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: ttt
      run: |
        ls
        mvn clean package
        cp ./src/docker/Dockerfile ./target/VESCollector-1.12.3-SNAPSHOT/
        cd ./target/VESCollector-1.12.3-SNAPSHOT/
        docker build -t ios-mcn-smo/ves-collector:1.12.3 .
